# ArgoCD Config
configs:
  secret:
    createSecret: true
    argocdServerAdminPassword: "$2a$10$FypmU/aJry8g/qchHs8zvudkZdSrrGv4MIQC8GRAkOR54Ok8AAINu"
  params:
    server.insecure: true

# Server Config
server:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
    ingressClassName: nginx
    hosts:
      - argocd.taskit.in
    tls:
      - hosts:
          - argocd.taskit.in
        secretName: argocd.taskit.in-tls
    https: true
